/* This code is part of RF Swift by @Penthertz
*  Author(s): Sébastien Dudek (@FlUxIuS)
 */

package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	common "penthertz/rfswift/common"
)

// GenManPages writes one section-1 troff man page per visible rfswift command
// into dir (rfswift.1, rfswift-container.1, ...). Called by tools/genman at
// package-build time, never at runtime. Generated by hand against cobra's
// public API rather than spf13/cobra/doc: cobra v1.10 split that package into
// a separate module precisely so CLIs don't have to carry its markdown
// converter in their dependency graph, and this project audits its modules.
func GenManPages(dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return genManTree(rootCmd, dir)
}

func genManTree(cmd *cobra.Command, dir string) error {
	page := filepath.Join(dir, manPageName(cmd)+".1")
	if err := os.WriteFile(page, []byte(manPage(cmd)), 0o644); err != nil {
		return err
	}
	for _, sub := range cmd.Commands() {
		if !sub.IsAvailableCommand() || sub.IsAdditionalHelpTopicCommand() {
			continue
		}
		if err := genManTree(sub, dir); err != nil {
			return err
		}
	}
	return nil
}

func manPageName(cmd *cobra.Command) string {
	return strings.ReplaceAll(cmd.CommandPath(), " ", "-")
}

// manEscape makes s safe as troff body text: printable backslashes, literal
// hyphens (so flags copy-paste back as ASCII "-"), and no line that troff
// would mistake for a request.
func manEscape(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\e")
	s = strings.ReplaceAll(s, "-", "\\-")
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if strings.HasPrefix(line, ".") || strings.HasPrefix(line, "'") {
			lines[i] = "\\&" + line
		}
	}
	return strings.Join(lines, "\n")
}

func manPage(cmd *cobra.Command) string {
	var b strings.Builder
	name := manPageName(cmd)

	// The empty date field keeps the output byte-identical across builds.
	fmt.Fprintf(&b, ".TH \"%s\" \"1\" \"\" \"RF Swift %s\" \"RF Swift Manual\"\n",
		strings.ToUpper(name), common.Version)
	// Some Short strings start with the command name ("rfswift - ..."); strip
	// it so NAME doesn't read "rfswift - rfswift - ...".
	short := strings.TrimPrefix(cmd.Short, cmd.Name()+" - ")
	fmt.Fprintf(&b, ".SH NAME\n%s \\- %s\n", manEscape(name), manEscape(short))
	fmt.Fprintf(&b, ".SH SYNOPSIS\n.B %s\n", manEscape(cmd.UseLine()))

	description := cmd.Long
	if description == "" {
		description = cmd.Short
	}
	fmt.Fprintf(&b, ".SH DESCRIPTION\n%s\n", manEscape(description))

	if cmd.Example != "" {
		fmt.Fprintf(&b, ".SH EXAMPLES\n.nf\n%s\n.fi\n", manEscape(cmd.Example))
	}

	writeManFlags(&b, "OPTIONS", cmd.NonInheritedFlags())
	writeManFlags(&b, "OPTIONS INHERITED FROM PARENT COMMANDS", cmd.InheritedFlags())

	var seeAlso []string
	if cmd.HasParent() {
		seeAlso = append(seeAlso, manPageName(cmd.Parent()))
	}
	for _, sub := range cmd.Commands() {
		if !sub.IsAvailableCommand() || sub.IsAdditionalHelpTopicCommand() {
			continue
		}
		seeAlso = append(seeAlso, manPageName(sub))
	}
	if len(seeAlso) > 0 {
		b.WriteString(".SH SEE ALSO\n")
		for i, ref := range seeAlso {
			separator := ","
			if i == len(seeAlso)-1 {
				separator = ""
			}
			fmt.Fprintf(&b, ".BR %s (1)%s\n", manEscape(ref), separator)
		}
	}
	return b.String()
}

func writeManFlags(b *strings.Builder, title string, flags *pflag.FlagSet) {
	if !flags.HasAvailableFlags() {
		return
	}
	fmt.Fprintf(b, ".SH %s\n", title)
	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		b.WriteString(".TP\n")
		names := "\\fB\\-\\-" + manEscape(f.Name) + "\\fR"
		if f.Shorthand != "" {
			names = "\\fB\\-" + f.Shorthand + "\\fR, " + names
		}
		if f.Value.Type() != "bool" {
			names += " \\fI" + manEscape(f.Value.Type()) + "\\fR"
		}
		b.WriteString(names + "\n")
		usage := f.Usage
		if f.DefValue != "" && f.DefValue != "false" && f.DefValue != "[]" {
			usage += " (default: " + f.DefValue + ")"
		}
		b.WriteString(manEscape(usage) + "\n")
	})
}
