name: Publish github release

on:
  push:
    tags: ["v*"]


permissions:
  contents: write

jobs:
  generate-artifacts:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
          workdir: go/rfswift
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
